server:
  port: 8082
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/exam
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

    username:
    password:


#      shaxsiy variable lar
jwt:
  access:
    secret: buMeningParolim
  refresh:
    secret: buRefreshniParoli
twilio:
  accountSID: ACb295fead92ee6b4b6cec8145cb705d2c
  authToken: ad127fc834928c39908a05a8f7e48282
  trialNumber: +18647744266